controller_list:
  - name: left_panda_arm_controller
    action_ns: follow_joint_trajectory
    joints:
      - panda_left_joint1
      - panda_left_joint2
      - panda_left_joint3
      - panda_left_joint4
      - panda_left_joint5
      - panda_left_joint6
      - panda_left_joint7
  - name: right_panda_arm_controller
    action_ns: follow_joint_trajectory
    joints:
      - panda_right_joint1
      - panda_right_joint2
      - panda_right_joint3
      - panda_right_joint4
      - panda_right_joint5
      - panda_right_joint6
      - panda_right_joint7
  - name: left_hand_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - panda_left_finger_joint1
      - panda_left_finger_joint2
  - name: right_hand_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - panda_right_finger_joint1
      - panda_right_finger_joint2
