# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_panda_arm
  joint_model_group_pose: left_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_left_joint1
    - panda_left_joint2
    - panda_left_joint3
    - panda_left_joint4
    - panda_left_joint5
    - panda_left_joint6
    - panda_left_joint7
    - panda_right_joint1
    - panda_right_joint2
    - panda_right_joint3
    - panda_right_joint4
    - panda_right_joint5
    - panda_right_joint6
    - panda_right_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - panda_left_joint1
    - panda_left_joint2
    - panda_left_joint3
    - panda_left_joint4
    - panda_left_joint5
    - panda_left_joint6
    - panda_left_joint7
    - panda_right_joint1
    - panda_right_joint2
    - panda_right_joint3
    - panda_right_joint4
    - panda_right_joint5
    - panda_right_joint6
    - panda_right_joint7
  gains:
    panda_left_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1