controller_list:
  - name: fake_left_comau_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - comau_left_joint_1
      - comau_left_joint_2
      - comau_left_joint_3
      - comau_left_joint_4
      - comau_left_joint_5
      - comau_left_joint_6
  - name: fake_right_comau_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - comau_right_joint_1
      - comau_right_joint_2
      - comau_right_joint_3
      - comau_right_joint_4
      - comau_right_joint_5
      - comau_right_joint_6
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses.
  - group: left_comau_arm
    pose: left_home
  - group: right_comau_arm
    pose: right_home