# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_comau_arm
  joint_model_group_pose: left_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - comau_left_joint_1
    - comau_left_joint_2
    - comau_left_joint_3
    - comau_left_joint_4
    - comau_left_joint_5
    - comau_left_joint_6
    - comau_right_joint_1
    - comau_right_joint_2
    - comau_right_joint_3
    - comau_right_joint_4
    - comau_right_joint_5
    - comau_right_joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_comau_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - comau_left_joint_1
      - comau_left_joint_2
      - comau_left_joint_3
      - comau_left_joint_4
      - comau_left_joint_5
      - comau_left_joint_6
  - name: right_comau_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - comau_right_joint_1
      - comau_right_joint_2
      - comau_right_joint_3
      - comau_right_joint_4
      - comau_right_joint_5
      - comau_right_joint_6