controller_list:
  - name: fake_left_iiwa_arm_controller
    type: $(arg execution_type)
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
  - name: fake_right_iiwa_arm_controller
    type: $(arg execution_type)
    joints:
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7
  - name: fake_left_hand_controller
    type: $(arg execution_type)
    joints:
      []
  - name: fake_right_hand_controller
    type: $(arg execution_type)
    joints:
      []
initial:  # Define initial robot poses.
  - group: left_iiwa_arm
    pose: home
  - group: right_iiwa_arm
    pose: home